# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  dockerId: sarahlaw007
  pswd: tobechanged1
  tag: $(Build.BuildNumber)

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- script: docker login -u $(dockerId) -p $(pswd)
- task: SSH@0
  inputs:
    sshEndpoint: 'sshTry1'
    runOptions: 'inline'
    inline: |
      cd Desktop/deployCodeADO
      ls
      rm -rf buildDeploy.sh
      rm -rf buildImage.sh
      rm -rf SarahSampleWeb2

      cat >> buildImage.sh <<EOF
      #!/bin/sh
      git clone https://github.com/SarahLaw007/SarahSampleWeb2.git
      cd SarahSampleWeb2
      docker build --no-cache -t samplepipelinetwo .
      EOF
      chmod +x buildImage.sh
      ./buildImage.sh
      
      cat >> buildDeploy.sh <<EOF
      #!/bin/sh
      tag=$(Build.BuildNumber)
      echo "\$tag"
      USERNAME=sarahlaw007
      PASSWORD=tobechanged1

      docker login -u "\$USERNAME" -p "\$PASSWORD"

      echo "TAGGING..."
      docker tag samplepipelinetwo sarahlaw007/sample-web-app2:"\$tag"

      echo "PUSHING..."
      docker push sarahlaw007/sample-web-app2:"\$tag"

      sudo su -  << EOF
      FILE=/home/devadmin/Desktop/trigger/samplepipeline2.txt

      if test -f /home/devadmin/Desktop/trigger/samplepipeline2.txt; then
          echo "Updating..."
          kubectl set image deployment/pipeline-demo2 pipeline-demo2=sarahlaw007/sample-web-app2:"\$tag" --record=true
          echo "Application updated: /$(date "+%Yy%mm%dd%Hh%Mm%Ss")" to this build $(Build.BuildNumber) >> /home/devadmin/Desktop/trigger/samplepipeline2.txt
      else 
          echo "Deploying new application..."
          kubectl run pipeline-demo2 --replicas=2 --image=sarahlaw007/sample-web-app2:"\$tag" --port=80
          kubectl expose deployment pipeline-demo2 --type=NodePort --name=pipeline-demo-service2
          echo "Application created: /$(date "+%Yy%mm%dd%Hh%Mm%Ss")" > /home/devadmin/Desktop/trigger/samplepipeline2.txt

      fi

      EOF
      ./execute.sh
