# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  dockerId: sarahlaw007
  pswd: Thomas1cat
  tag: $(Build.BuildNumber)


steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- script: docker login -u $(dockerId) -p $(pswd)
  displayName: 'Logged in... Now building and deploying...'
- script: docker build --no-cache -t samplepipelinetwo .
  displayName: 'Now Tagging and Pushing'
- script: tag=$(date "+%Yy%mm%dd%Hh%Mm%Ss")
- script: echo $(tag)
- script: docker tag samplepipelinetwo sarahlaw007/sample-web-app2:$(tag)
- script: docker push sarahlaw007/sample-web-app2:$(tag)
- task: SSH@0
  inputs:
    sshEndpoint: 'sshTry1'
    runOptions: 'inline'
    inline: |
      cd Desktop/deployCodeADO
      ls
