# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  dockerId: sarahlaw007
  pswd: Thomas1cat
  imageName: 


steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- script: docker login -u $(dockerId) -p $(pswd)
  displayName: 'Logged in... Now building and deploying...'
- script: docker build --no-cache -t samplepipelinetwo .
  displayName: 'Now Tagging and Pushing'
-script: tag=$(date "+%Yy%mm%dd%Hh%Mm%Ss")
-script: echo "$tag"
-script: docker tag samplepipeline sarahlaw007/sarah_sample_web_app:"$tag"
-script: docker push sarahlaw007/sarah_sample_web_app:"$tag"
